In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import japanize_matplotlib
import scipy
from scipy import stats
from numpy.random import randn

C:\Users\Public\Anaconda3\lib\site-packages\japanize_matplotlib\japanize_matplotlib.py:15: MatplotlibDeprecationWarning: 
The createFontList function was deprecated in Matplotlib 3.2 and will be removed two minor releases later. Use FontManager.addfont instead.
  font_list = font_manager.createFontList(font_files)


In [2]:
N = 1000
p = 2
X = randn(N, p)
X = np.insert(X, 0, 1, axis=1)
beta = randn(p+1)
y = []
prob = 1 / (1 + np.exp(X @ beta))
for i in range(N):
    if np.random.rand(1) > prob[i]:
        y.append(1)
    else:
        y.append(-1)
beta

array([ 0.468713  , -0.1418133 , -1.24061071])

In [14]:
beta = np.inf
gamma = randn(p+1)
print(gamma)
while np.sum((beta - gamma)**2) > 0.001:
    beta = gamma
    s = X @ beta
    v = np.exp(- s * y)
    u = y * v / (1 + v)
    w = v / ((1 + v)**2)
    W = np.diag(w)
    z = X @ beta + np.linalg.inv(W) @ u
    gamma = np.linalg.inv(X.T @ W @ X) @ X.T @ W @ z
    print(gamma)

[-0.88235113 -0.21262263 -0.94254473]
[ 0.61953913 -0.01006237 -0.76589933]
[ 0.46687718 -0.09224416 -1.09529899]
[ 0.46452993 -0.09676225 -1.14861121]
[ 0.46463971 -0.09682045 -1.1499024 ]
